### PR TITLE
Add notebook with comparison functions

### PR DESCRIPTION
**Pull request by rodrigogiraoserrao**
Please let me know if this notebook is formatted and worded according to your standards; I also expect your feedback on the content.

### CODE REVIEW

**Comment by abrudz** [comment]
We really like the gist of the content.
1. I don't think you need the tables of content or internal hyperlinks. The document should read as a "story", not as a webpage. Instead, maybe begin with an introductory paragraph, describing what you will go through.
1. You should begin with an introduction to true and false being 1 and 0 in APL, and maybe (later?) spell out some benefits of that, (not just show the `+/` example).
1. Please split code blocks so each block causes a single output.
1. Avoid `⎕←` to coerce display of an assigned value, instead going for a two-line block that first assigns, then just mentions the variable so it is printed. This is both for clarity and so current TryAPL can play along. (That said, we are planning to enhance TryAPL to handle pretty much any code.)
1. While "scalar means they penetrate into nested arrays all the way down to the scalars composing said arrays" they also auto-map arrays and extend scalars. Also note that even nested arrays are comprised of scalars, but these functions go down to the *simple* scalars.
1. APL symbols in text blocks are inconsistently backticked.
1. When you point out that non-numbers cannot be compared, maybe at least mention that one can use `ComparisonFn/⍋`  to compare anything.
1. You don't have a section on using the comparison functions as Boolean functions, but maybe that's better suited for a separate notebook together with `∧∨⍲⍱`?

**Comment by rodrigogiraoserrao** [comment]
Thanks for the feedback;

I will address your bullet points and come back to you. Please confirm that for 6. I should consistently backtick all of the symbols (instead of consistently removing backticks). As for 8, I would say a notebook on boolean functions is more appropriate.

**Comment by abrudz** [comment]
I'd say backtick the symbols when talking about the APL functions and use MathJax (or just leave as text) when talking about the corresponding traditional mathematics. I agree about your assesment of Boolean fns.

**Comment by rodrigogiraoserrao** [comment]
@abrudz I think this addresses your feedback. Please let me know how you feel about my commit.

**Pull request closed without merging**
