### PR TITLE
Add Plotting with SharpPlot notebook

### PR DESCRIPTION
**Pull request by yiyus**

### CODE REVIEW

**Comment by abrudz** [comment]
> `3500⌶`

Isn't it better to use `]html` as that works cross-platform?

> using a dfn or a tacit function is not possible because the SP SetColors method does not return anything

It is possible, but awkward. (And yes, we should fix that.)

**Comment by yiyus** [comment]
I thought `3500⌶` was cross-platform because jupyter notebooks used RIDE behind the scenes everywhere, but if I am wrong, `]html` would indeed be a better option. The reason I used the I-beam function is because I cannot call `]html` from the `Plot` function, so either the `Plot` function should return SVG and then the user should always call `]html` on the result, or I would need to define a new user command (which I wanted to avoid just for simplicity). Is there another solution I'm missing? If there is any potential problem in any platform, I will change it to use `]html`.

About using functions with no return values outside of tradfns, I am aware there is some workaround, but I did not find any good reason to not just use a tradfn here. Maybe the reasoning should be better explained.

Thanks for the comments!

**Comment by abrudz** [comment]
Jupyter Notebook doesn't actually use RIDE, but the RIDE protocol; the JSON schema that RIDE (and others!) uses to communicate with the interpreter. `]html` decides whether to use `3500⌶` to send HTML via the protocol (which RIDE and the Jupiter kernel each handle in their own way) or create an HTMLRenderer (CEF) instance. Only the latter option is available to the TTY version (TUI) and the native Windows IDE. You can call user commands under program control with `⎕SE.UCMD'cmdname args'`. Now that you mention it, we should move the core of that user command into a utility function, so it can be used directly for cross-platform rendering under program control. Thanks!

You don't need to say how calling result-less functions can be done outside tradfns, but maybe just phrase it as "using a dfn or a tacit function is awkward because the SP SetColors method does not return anything"

**Comment by yiyus** [comment]
Ok. That makes perfect sense. I pushed a new version using `]html` and with some other small fixes. Thank you again!

**Comment by rikedyp** [comment]
I'm going through your notebooks and will email with more detailed comments, but regarding the `]html` user command:
Please never use `⎕SE.UCMD` to call user commands programmatically. Instead, your operator can return the svg. Then use `]html` when you call the `Plot` function.

`]html 'red' 'blue' ('x'Plot'y') ('sin' sin) ('cos' cos)                                ⍝ sin and cos, with colors`

```APL
]dinput
svg←{colors}(xlabel Plot ylabel) data;InitCauseway;Causeway;System;sp;fc;fl;fs;fmt;names;xa;xw;ya;yw
⍝ eg: 'red' 'blue' ('xlabel'Plot'ylabel') ('series1' (y1 x1)) ('series2' (y2 x2))

⍝ Init
:If 0=⎕NC'Causeway'
'InitCauseway'⎕CY'sharpplot'
InitCauseway ⍬
:EndIf
sp←⎕NEW Causeway.SharpPlot

⍝ Format
sp.XAxisStyle←Causeway.XAxisStyles.GridLines
sp.YAxisStyle←Causeway.YAxisStyles.(GridLines+AtEndCaption)
fc fl fs ← System.Drawing.Color.Black 9.5 7.5 ⍝ font color, large size, small size
sp.SetXCaptionFont fl fc ⋄ sp.SetXLabelFont fs fc
sp.SetYCaptionFont fl fc ⋄ sp.SetYLabelFont fs fc
sp.SetKeyFont fl fc
fmt←'0.00' ⋄ sp.XLabelFormat←fmt ⋄ sp.YLabelFormat←fmt
sp.SetPenWidths 2

⍝ Curves
:If 0=⎕NC'colors'
    colors ← ⊂'black'
:EndIf
:If ¯4<≡data
    names data←data
    data←,⊂data
:Else
    names data←↓⍉↑data ⍝ names and data
:EndIf
colors ← (≢data)⍴⊆colors ⍝ "scalar extension"

⍝ Labels
sp.XCaption←,xlabel
sp.YCaption←,ylabel,⎕UCS 10 ⍝ add newline to leave some space
sp.SetKeyText⊂names

⍝ Limits
ya xa←⌊⌿⌊/¨↑data
yw xw←⌈⌿⌈/¨↑data
sp.SetYRange ya yw
sp.SetXRange xa xw

⍝ Plot and display
:For i :In ⍳≢data
    sp.SetColors i⌷colors 
    sp.DrawLineGraph i⊃data
:EndFor
svg←sp.RenderSvg Causeway.SvgMode.FixedAspect
```

**Pull request merged**
